# Generated by Django 3.0.5 on 2021-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='attendance_taken',
            field=models.BooleanField(default=False),
        ),
    ]
