# Generated by Django 3.0.5 on 2021-02-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210219_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='studentCount',
            new_name='student_count',
        ),
    ]
