# Generated by Django 3.0.5 on 2021-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210219_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_given',
            field=models.BooleanField(default=False),
        ),
    ]
