# Generated by Django 3.0.5 on 2021-03-06 06:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210302_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('max_students_allowed', models.IntegerField(default=0)),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
