# Generated by Django 3.0.5 on 2021-03-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210306_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(default='01476803118', max_length=15),
        ),
    ]
